/**
 * Issue #3973: `skipConnectionRate` selects the targeted skip-connection
 * operator, and `0` — the default — must be indistinguishable from a build
 * without the operator.
 *
 * The golden sequence below was captured from base commit `e02d33af` (the
 * milestone branch tip before this change) by seeding the RNG and asking the
 * `Mutator` for 50 mutation methods, then reading the next three RNG draws. It
 * is pinned here rather than compared against a freshly computed value, so the
 * test measures new-versus-historical rather than default-versus-explicit-zero:
 * an operator that consumed even one RNG draw at rate `0` would shift the tail.
 *
 * Pinning the raw draw stream is deliberate and is the only way to demonstrate
 * "consumes no randomness", which the issue asks for as bit-identity on a fixed
 * seed. It therefore also pins the *default mutation mix*: a legitimate change
 * to `Mutation.ALL`, to `selectMutationMethod`'s weighting, or to the RNG itself
 * will fail these two tests, and the fixture is then regenerated by running
 * {@link selectionProbe} on a checkout of the commit being compared against and
 * pasting the result — not by relaxing the assertion.
 */
import { assert, assertEquals, assertThrows } from "@std/assert";
import { Creature } from "@creature";
import { createNeatConfig } from "@config/NeatConfig.ts";
import { ConfigurationError } from "@errors/ConfigurationError.ts";
import { Mutation } from "@neat/Mutation.ts";
import { Mutator } from "@neat/Mutator.ts";
import {
  createSeededRng,
  getRandomNumberGenerator,
  setRandomNumberGenerator,
} from "@utils/RandomNumberGenerator.ts";
import { withRngTestLock } from "../_rngTestLock.ts";
import { chainCreature, neuronIndex } from "../mutate/_chainCreature.ts";

/** Mutation methods commit `e02d33af` selects for seed 3973. */
const HISTORICAL_SELECTION: readonly string[] = [
  "SUB_NODE",
  "MOD_WEIGHT",
  "SUB_NODE",
  "MOD_BIAS",
  "MOD_WEIGHT",
  "SUB_CONN",
  "MOD_BIAS",
  "MOD_BIAS",
  "MOD_BIAS",
  "SUB_CONN",
  "SUB_CONN",
  "MOD_WEIGHT",
  "MOD_WEIGHT",
  "MOD_BIAS",
  "MOD_BIAS",
  "MOD_BIAS",
  "MOD_BIAS",
  "SUB_NODE",
  "MOD_BIAS",
  "MOD_WEIGHT",
  "MOD_WEIGHT",
  "MOD_BIAS",
  "ADD_CONN",
  "MOD_BIAS",
  "MOD_BIAS",
  "ADD_CONN",
  "MOD_WEIGHT",
  "SUB_CONN",
  "SWAP_NODES",
  "MOD_BIAS",
  "MOD_WEIGHT",
  "MOD_BIAS",
  "MOD_BIAS",
  "MOD_WEIGHT",
  "MOD_WEIGHT",
  "MOD_BIAS",
  "MOD_WEIGHT",
  "MOD_SQUASH",
  "MOD_WEIGHT",
  "MOD_WEIGHT",
  "MOD_BIAS",
  "ADD_NODE",
  "MOD_WEIGHT",
  "MOD_BIAS",
  "MOD_WEIGHT",
  "MOD_BIAS",
  "MOD_SQUASH",
  "MOD_WEIGHT",
  "MOD_WEIGHT",
  "MOD_BIAS",
];

/** The next three RNG draws after that selection, on the same commit. */
const HISTORICAL_TAIL: readonly number[] = [
  0.6856675485983662,
  0.9218067199684751,
  0.5312303564361699,
];

/** Draw 50 mutation methods for seed 3973, then read three RNG values. */
function selectionProbe(
  overrides: Record<string, unknown>,
): { names: string[]; tail: number[] } {
  const config = createNeatConfig({
    populationSize: 10,
    mutation: Mutation.ALL,
    ...overrides,
  });
  const mutator = new Mutator(config);
  const creature = new Creature(3, 2, { layers: [{ count: 4 }] });

  setRandomNumberGenerator(createSeededRng(3973));
  const names: string[] = [];
  for (let i = 0; i < HISTORICAL_SELECTION.length; i++) {
    names.push(mutator.selectMutationMethod(creature).name);
  }
  const rng = getRandomNumberGenerator();
  return { names, tail: [rng.random(), rng.random(), rng.random()] };
}

Deno.test("skipConnectionRate - the default is identical to commit e02d33af", async () => {
  await withRngTestLock(() => {
    const previous = getRandomNumberGenerator();
    try {
      const probe = selectionProbe({});
      assertEquals(probe.names, [...HISTORICAL_SELECTION]);
      assertEquals(probe.tail, [...HISTORICAL_TAIL]);
    } finally {
      setRandomNumberGenerator(previous);
    }
  });
});

Deno.test("skipConnectionRate - an explicit 0 is identical to commit e02d33af", async () => {
  await withRngTestLock(() => {
    const previous = getRandomNumberGenerator();
    try {
      const probe = selectionProbe({ skipConnectionRate: 0 });
      assertEquals(probe.names, [...HISTORICAL_SELECTION]);
      assertEquals(
        probe.tail,
        [...HISTORICAL_TAIL],
        "rate 0 must consume no randomness of its own",
      );
      assert(
        !probe.names.includes(Mutation.ADD_SKIP_CONN.name),
        "and must never select the operator",
      );
    } finally {
      setRandomNumberGenerator(previous);
    }
  });
});

Deno.test("skipConnectionRate - 1 selects the skip operator every time", async () => {
  await withRngTestLock(() => {
    const previous = getRandomNumberGenerator();
    try {
      const probe = selectionProbe({ skipConnectionRate: 1 });
      assertEquals(
        new Set(probe.names),
        new Set([Mutation.ADD_SKIP_CONN.name]),
      );
    } finally {
      setRandomNumberGenerator(previous);
    }
  });
});

Deno.test("skipConnectionRate - a fractional rate mixes the operator in", async () => {
  await withRngTestLock(() => {
    const previous = getRandomNumberGenerator();
    try {
      const probe = selectionProbe({ skipConnectionRate: 0.5 });
      const skips = probe.names.filter((n) =>
        n === Mutation.ADD_SKIP_CONN.name
      ).length;
      const fraction = skips / probe.names.length;
      assert(
        fraction > 0.25 && fraction < 0.75,
        `a rate of 0.5 should select the operator roughly half the time, got ${fraction}`,
      );
    } finally {
      setRandomNumberGenerator(previous);
    }
  });
});

Deno.test("skipConnectionRate - the operator stays out of Mutation.ALL and FFW", () => {
  const all = Mutation.ALL.map((m) => m.name);
  const ffw = Mutation.FFW.map((m) => m.name);
  assert(
    !all.includes(Mutation.ADD_SKIP_CONN.name),
    "an existing `mutation: ALL` config must not gain the operator",
  );
  assert(!ffw.includes(Mutation.ADD_SKIP_CONN.name));
});

Deno.test("skipConnectionRate - a full mutation batch adds the bypass and stays valid", async () => {
  await withRngTestLock(() => {
    const previous = getRandomNumberGenerator();
    try {
      setRandomNumberGenerator(createSeededRng(3973));
      const creature = chainCreature(6);
      const entry = neuronIndex(creature, "run-0");
      const output = neuronIndex(creature, "output-0");
      const before = creature.synapses.length;

      const config = createNeatConfig({
        populationSize: 10,
        mutation: Mutation.ALL,
        mutationRate: 1,
        mutationAmount: 1,
        skipConnectionRate: 1,
      });
      const mutator = new Mutator(config);
      mutator.mutate([creature]);

      assertEquals(creature.synapses.length, before + 1);
      assert(
        creature.hasConnection(entry, output),
        "the batch should have added the bypass around the run",
      );
      creature.validate();
    } finally {
      setRandomNumberGenerator(previous);
    }
  });
});

Deno.test("skipConnectionRate - the config refuses values out of range", () => {
  assertThrows(
    () => createNeatConfig({ populationSize: 10, skipConnectionRate: 1.5 }),
    ConfigurationError,
    "Skip connection rate",
  );
  assertThrows(
    () => createNeatConfig({ populationSize: 10, skipMinRunLength: 1 }),
    ConfigurationError,
    "Skip minimum run length",
  );
  assertThrows(
    () => createNeatConfig({ populationSize: 10, skipMinRunLength: 2.5 }),
    ConfigurationError,
    "Skip minimum run length must be an integer",
  );
});

Deno.test("skipConnectionRate - skipMinRunLength reaches the operator", async () => {
  await withRngTestLock(() => {
    const previous = getRandomNumberGenerator();
    try {
      setRandomNumberGenerator(createSeededRng(3973));
      // A run of six is bypassed at the default minimum of four, and left alone
      // when the minimum is raised above it.
      const creature = chainCreature(6);
      const before = creature.synapses.length;
      const config = createNeatConfig({
        populationSize: 10,
        mutation: Mutation.ALL,
        mutationRate: 1,
        mutationAmount: 1,
        skipConnectionRate: 1,
        skipMinRunLength: 7,
      });
      new Mutator(config).mutate([creature]);
      assertEquals(
        creature.synapses.length,
        before,
        "a minimum above the run length must leave the creature alone",
      );
    } finally {
      setRandomNumberGenerator(previous);
    }
  });
});
