/**
 * One-off practice verification for Issue #3238 (parent #3233).
 *
 * Runs a representative multi-generation `evolveDataSet` training job with the
 * native batch `rust_scorer` enabled and captures, from a REAL run, the four
 * evidence items the parent issue asks for:
 *
 *   1. The per-generation NEAT-AI partition log line
 *      `[NEAT-AI] Batch scorer partition: N forwardOnly batched, M recurrent
 *      per-creature`.
 *   2. Exactly one `rust_scorer` process spawned per generation for the
 *      forwardOnly subset — measured at OS process-spawn granularity by
 *      wrapping the scorer binary in a shim that appends one line per launch.
 *   3. Single-pass-over-data evidence per batch invocation — the scorer's
 *      `scorerUtilisation.batchScorerInvocations` equals the generation count
 *      (one streamed pass per invocation; the streaming guarantee lives in
 *      NEAT-AI-scorer `multi_score.rs`, one `for_each_read_chunk` call).
 *   4. The `scorerUtilisation` block, written into a `result.json` artifact in
 *      the same shape the GRQ worker serialises into GRQ-cluster/result.json.
 *
 * Any discrepancy (unexpected fallback, batch path not taken) is printed
 * loudly and reflected in the artifact rather than hidden (Issue #3234).
 *
 * Usage:
 *   NEAT_AI_RUST_SCORER_BINARY_PATH=/abs/path/to/rust_scorer \
 *     deno run -A scripts/verifyBatchScorerUtilisation3238.ts [outDir]
 *
 * The wrapper shim and the batch flags are set by this script; the caller only
 * supplies the real binary path (and an optional output directory).
 */

import { Creature } from "@creature";
import type { DataRecordInterface } from "@architecture/DataSet.ts";
import type {
  GenerationCompleteEvent,
  TrainingEvent,
} from "@config/TrainingEvent.ts";
import { getLogger } from "@utils/Logger.ts";
import { initWasmActivation } from "@wasm/mod.ts";
import {
  classifySpawns,
  detectDiscrepancies,
} from "./verifyBatchScorerUtilisationLib.ts";

const GENERATIONS = 12;
const POPULATION = 24;
const INPUTS = 3;

/** Build a small deterministic feed-forward regression dataset. */
function buildDataSet(rows: number): DataRecordInterface[] {
  const data: DataRecordInterface[] = [];
  for (let i = 0; i < rows; i++) {
    const a = (i % 7) / 7;
    const b = (i % 5) / 5;
    const c = (i % 3) / 3;
    // A smooth deterministic target so scores are finite and comparable.
    const y = (a * 0.5 + b * 0.3 - c * 0.2 + 1) / 2;
    data.push({
      input: new Float32Array([a, b, c]),
      output: new Float32Array([y]),
    });
  }
  return data;
}

/**
 * Write a tiny shell shim that records one line per launch (timestamp + argv)
 * into `logPath`, then exec()s the real binary transparently. This measures
 * `rust_scorer` process spawns at the OS level — the strongest possible
 * "one invocation per generation" evidence.
 */
async function writeScorerShim(
  realBinary: string,
  logPath: string,
): Promise<string> {
  const shimPath = await Deno.makeTempFile({
    prefix: "rust-scorer-shim-",
    suffix: ".sh",
  });
  const script = `#!/usr/bin/env bash
# Auto-generated by verifyBatchScorerUtilisation3238.ts — records each launch.
printf '%s\\t%s\\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*" >> ${
    JSON.stringify(logPath)
  }
exec ${JSON.stringify(realBinary)} "$@"
`;
  await Deno.writeTextFile(shimPath, script);
  await Deno.chmod(shimPath, 0o755);
  return shimPath;
}

async function main(): Promise<void> {
  const realBinary = Deno.env.get("NEAT_AI_RUST_SCORER_BINARY_PATH");
  if (!realBinary) {
    console.error(
      "FATAL: set NEAT_AI_RUST_SCORER_BINARY_PATH to the rust_scorer binary.",
    );
    Deno.exit(2);
  }
  // Fail loud if the binary is missing rather than silently falling back.
  try {
    const stat = await Deno.stat(realBinary);
    if (!stat.isFile) throw new Error("not a regular file");
  } catch (err) {
    console.error(
      `FATAL: rust_scorer binary unusable at ${realBinary}: ${err}`,
    );
    Deno.exit(2);
  }

  await initWasmActivation();

  const outDir = Deno.args[0] ?? "docs/evidence";
  await Deno.mkdir(outDir, { recursive: true });

  const spawnLog = await Deno.makeTempFile({
    prefix: "rust-scorer-spawns-",
    suffix: ".log",
  });
  await Deno.writeTextFile(spawnLog, "");
  const shimPath = await writeScorerShim(realBinary, spawnLog);

  // Enable the native batch scorer for this process only.
  Deno.env.set("NEAT_AI_RUST_SCORER_ENABLED", "true");
  Deno.env.set("NEAT_AI_RUST_SCORER_BATCH", "true");
  Deno.env.set("NEAT_AI_RUST_SCORER_BINARY_PATH", shimPath);

  // Capture the per-generation partition log lines emitted by Fitness.ts.
  // The logger is passed via NeatOptions so it survives the internal
  // `setLogger(config.logger)` call in createNeatConfig (Issue #1398).
  const partitionLines: string[] = [];
  const base = getLogger();
  const capturingLogger = {
    debug: (...a: unknown[]) => base.debug(...a),
    info: (...a: unknown[]) => {
      const msg = a.map((x) => String(x)).join(" ");
      if (msg.includes("Batch scorer partition")) partitionLines.push(msg);
      base.info(...a);
    },
    warn: (...a: unknown[]) => base.warn(...a),
    error: (...a: unknown[]) => base.error(...a),
  };

  const genEvents: GenerationCompleteEvent[] = [];
  const creature = new Creature(INPUTS, 1, { layers: [{ count: 4 }] });
  const dataSet = buildDataSet(96);

  console.info(
    `[verify] Running ${GENERATIONS} generations, population ${POPULATION}, ` +
      `native batch rust_scorer via shim -> ${realBinary}`,
  );

  const result = await creature.evolveDataSet(dataSet, {
    iterations: GENERATIONS,
    targetError: 0, // never met — run the full generation budget
    populationSize: POPULATION,
    threads: 1,
    logger: capturingLogger,
    onTrainingEvent: (event: TrainingEvent) => {
      if (event.kind === "generation_complete") genEvents.push(event);
    },
  });

  const util = result.scorerUtilisation;

  // Count actual OS-level scorer spawns from the shim log. The bridge probes
  // the binary once with `--help` to detect `--cost` support (Issue #2745);
  // that probe is not a scoring pass, so classify it out. Every remaining
  // launch is a batch scoring invocation (one creatures_dir + data_dir).
  const spawnLines = (await Deno.readTextFile(spawnLog)).split("\n");
  const { probe: probeSpawns, batch: batchSpawns } = classifySpawns(spawnLines);

  // Discrepancy checks — fail loud, never hide.
  const discrepancies = detectDiscrepancies(
    util,
    partitionLines.length,
    batchSpawns.length,
    probeSpawns.length,
  );

  const report = {
    issue: 3238,
    parent: 3233,
    generatedBy: "scripts/verifyBatchScorerUtilisation3238.ts",
    realBinary,
    run: {
      configuredIterations: GENERATIONS,
      aggregatedGenerations: util.generations,
      populationSize: POPULATION,
      inputs: INPUTS,
      finalError: result.error,
      finalScore: result.score,
      timeMs: result.time,
    },
    generationCompleteEvents: genEvents.length,
    // Evidence 1: partition log lines (one per generation).
    partitionLines,
    // Evidence 2: OS-level scorer process spawns (one batch spawn per
    // generation, plus one one-off `--help` cost probe).
    osScorerSpawnsTotal: batchSpawns.length + probeSpawns.length,
    osBatchScorerSpawns: batchSpawns.length,
    osProbeSpawns: probeSpawns.length,
    osScorerSpawnSample: [
      ...probeSpawns.slice(0, 1),
      ...batchSpawns.slice(0, 2),
    ],
    // Evidence 3 & 4: the run-level scorerUtilisation block.
    scorerUtilisation: util,
    discrepancies,
  };

  const resultPath = `${outDir}/verify-3238-result.json`;
  await Deno.writeTextFile(resultPath, JSON.stringify(report, null, 2) + "\n");

  console.info("\n===== VERIFY #3238 SUMMARY =====");
  console.info(`generations                 : ${util.generations}`);
  console.info(`partition log lines         : ${partitionLines.length}`);
  console.info(`OS batch scorer spawns      : ${batchSpawns.length}`);
  console.info(`OS --help probe spawns      : ${probeSpawns.length}`);
  console.info(`batchScorerInvocations      : ${util.batchScorerInvocations}`);
  console.info(`creaturesBatchScored        : ${util.creaturesBatchScored}`);
  console.info(
    `creaturesPerCreatureScored  : ${util.creaturesPerCreatureScored}`,
  );
  console.info(
    `batchFallbackGenerations    : ${util.batchFallbackGenerations}`,
  );
  console.info(`result artifact             : ${resultPath}`);
  if (partitionLines[0]) {
    console.info(`sample partition line       : ${partitionLines[0]}`);
  }

  // Clean up temp shim + spawn log (artifact already captured).
  await Deno.remove(shimPath).catch(() => {});
  await Deno.remove(spawnLog).catch(() => {});

  if (discrepancies.length > 0) {
    console.error("\n!!! DISCREPANCIES DETECTED (verification FAILED) !!!");
    for (const d of discrepancies) console.error(` - ${d}`);
    Deno.exit(1);
  }
  console.info(
    "\nAll checks passed: batch path used, one invocation/generation.",
  );
}

if (import.meta.main) {
  await main();
}
