name: Semgrep

on:
  pull_request:
    branches: ["Develop"]

permissions:
  contents: read

jobs:
  semgrep:
    name: Semgrep SAST scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      # actions/checkout@v4.3.1
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - run: semgrep ci --config p/default
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
