name: "Spelling"
on:
  pull_request:
    branches:
      - Develop

jobs:
  spellcheck: # run the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v6
        with:
          # Specify the files to check
          files: "**/*.{md,html,js,ts,css,sh}"
          config: "docs/cspell.json"
